import { describe, it, expect } from 'vitest'
import { generateTokenCss } from './css-generator.js'

describe('generateTokenCss', () => {
  it('contains :root { block', () => {
    const tokens = { '--color-primary': '#0ea5e9' }
    const css = generateTokenCss(tokens)
    expect(css).toContain(':root {')
  })

  it('contains correct --var: value; lines', () => {
    const tokens = {
      '--color-brand-50': '#f0f9ff',
      '--color-brand-500': '#0ea5e9',
    }
    const css = generateTokenCss(tokens)
    expect(css).toContain('  --color-brand-50: #f0f9ff;')
    expect(css).toContain('  --color-brand-500: #0ea5e9;')
  })

  it('includes header comment', () => {
    const tokens = { '--color-primary': '#0ea5e9' }
    const css = generateTokenCss(tokens)
    expect(css).toContain('/* Auto-generated by blokos')
  })

  it('closes :root block', () => {
    const tokens = { '--color-primary': '#0ea5e9' }
    const css = generateTokenCss(tokens)
    expect(css).toContain('}')
  })

  it('handles empty token map', () => {
    const css = generateTokenCss({})
    expect(css).toContain(':root {')
    expect(css).toContain('}')
  })
})
