import type { TokenMap } from './token-reader.js'

/**
 * Generates :root { ... } CSS block from a TokenMap.
 */
export function generateTokenCss(tokens: TokenMap): string {
  const lines: string[] = []

  lines.push('/* Auto-generated by blokos — do not edit manually */')
  lines.push(':root {')

  for (const [varName, value] of Object.entries(tokens)) {
    lines.push(`  ${varName}: ${value};`)
  }

  lines.push('}')
  lines.push('')

  return lines.join('\n')
}
